[build]
builder = "nixpacks"
installCommand = "pnpm install"

[deploy]
startCommand = "pnpm start"

[nixpacks]
nodejs = "18"

[[services]]
internalPort = 3002
env = ["NODE_ENV", "PRIVATE_KEY", "ANTHROPIC_API_KEY"]